import { componentCategory } from "../constants/constants.js";

export const mockComponents = [
  {
    name: "Arduino Uno R3",
    image: "https://cdn.example.com/components/arduino-uno.jpg",
    description: "ATmega328P based microcontroller board",
    component_working: 12,
    component_not_working: 1,
    component_in_use: 4,
    remark: "Popular for prototyping",
    category: componentCategory.MICRO_CONTROLLER,
  },
  {
    name: "DHT11 Sensor",
    image: "https://cdn.example.com/components/dht11.jpg",
    description: "Humidity and temperature sensor",
    component_working: 20,
    component_not_working: 2,
    component_in_use: 6,
    remark: "Entry-level environmental sensor",
    category: componentCategory.SENSOR,
  },
  {
    name: "L298N Motor Driver",
    image: "https://cdn.example.com/components/l298n.jpg",
    description: "Dual H-bridge motor driver module",
    component_working: 9,
    component_not_working: 1,
    component_in_use: 3,
    remark: "Used in robotics labs",
    category: componentCategory.MOTOR_DRIVER,
  },
  {
    name: "Servo Motor SG90",
    image: "https://cdn.example.com/components/sg90.jpg",
    description: "Micro servo motor",
    component_working: 18,
    component_not_working: 3,
    component_in_use: 8,
    remark: "Requires stable 5V supply",
    category: componentCategory.ACTUATOR,
  },
  {
    name: "ESP8266 WiFi Module",
    image: "https://cdn.example.com/components/esp8266.jpg",
    description: "Low-cost WiFi module",
    component_working: 14,
    component_not_working: 1,
    component_in_use: 5,
    remark: "Used for IoT projects",
    category: componentCategory.COMMUNICATION,
  },
];
